// Code generated by "stringer -type=StatusCode -linecomment"; DO NOT EDIT.

package libhttp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-200]
	_ = x[NotFound-404]
}

const (
	_StatusCode_name_0 = "OK"
	_StatusCode_name_1 = "Not Found"
)

func (i StatusCode) String() string {
	switch {
	case i == 200:
		return _StatusCode_name_0
	case i == 404:
		return _StatusCode_name_1
	default:
		return "StatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
